### ISSUE TITLE
Hack needed for building on Linux/Unix

### ISSUE THREAD

**Issue by petesoper** [AriZuu/wiced-driver#1]
The wiced.patch operation described in the README.md instructions fails on Linux because some of the files have CRLF line endings (and so they don't match what patch is expecting). Here's a quick hack that was tested on Linux to run in the directory prior to patch to switch the text file lines so they match. This script can take a long time to traverse the SDK tree with possibly long pauses: be careful not to interrupt it.

<pre>
#!/bin/sh
# Fix for DOS/Windows files expected to be Unix/Linux files.
# Recursively find all the text files with CRLF endings and make them LF.
# Be careful not to kill this script before it finishes!
# Tested on Ubuntu 13.10

if [ "`which dos2unix` " = " " ] ; then
  echo "Install dos2unix and run this again"
  exit 1
fi

find . -type f | while read file ; do
  file "$file" | grep -q "ASCII text, with CRLF line terminators" 
  if [ $? -eq 0 ] ; then
    dos2unix "$file"
  fi
done
</pre>

**Comment by AriZuu** [comment]
Good point. I didn't notice that myself, as I have SDK in internal git repository where the line endings are already fixed by git (ie. I have core.autocrlf = input).

**Comment by AriZuu** [comment]
Alternative way to solve this with git would be

<pre>
cd WICED-SDK-3.3.1
git init
git config core.autocrlf input
git add .
warning: CRLF will be replaced by LF in ....
The file will have its original line endings in your working directory.
git commit -a -m "fix line endings."
git rm --cached -r .
git reset --hard
</pre>

**Comment by AriZuu** [comment]
This is now documented in README.
